### ISSUE TITLE
New CUDNN release

### ISSUE THREAD

**Issue by Felix-neko** [hannes-brt/cudnn-python-wrappers#6] opened 2015-01-12 10:32 UTC
Guten morgen! 
There is a new CUDNN release (R2). Aren't you going to support it?

Just now it gives the following error:

    import libcudnn as cudnn
    File "/usr/local/lib/python3.4/dist-packages/libcudnn.py", line 311, in <module>
    _libcudnn.cudnnCreateTensor4dDescriptor.restype = int
    File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
    File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: /usr/local/cuda-6.5/lib64/libcudnn.so: undefined symbol: cudnnCreateTensor4dDescriptor

UPD: As I can see, the API has changed a bit.

**Comment by hannes-brt** [comment] 2015-01-12 15:29
This is a duplicate of #4.

**Closed by hannes-brt** 2015-01-12 15:29 UTC
